### ISSUE TITLE
Question about hyperparameters

### ISSUE THREAD

**Issue by gserpep** [SaraBabakN/MFCL-NeurIPS23#4]
Hello,

I was checking something when I realised the `syn_size` parameter is set to 128. From my understanding, this hyperparameter controls the size of the synthetic mini-batch. However – according to Section F of the appendix – this value is set to 32 for all the experiments. Am I missing something? Many thanks for any clarification!

Best,
Giuseppe

**Comment by gserpep** [comment]
Also, I am confused about the `server_ss` parameter, could you please clarify what it does and how to use it? Many thanks!

**Comment by SaraBabakN** [comment]
Hi Guiseppe, 

You are correct about the syn_size, and its values should be 32. I think 128 is a problem with the code. 

Also, server_ss is the server sampling size and is responsible for the batch size in training the generative model itself.


Best,
Sara

**Comment by SaraBabakN** [comment]
Actually, server_ss is the server sampling size and is responsible for the batch size in training the generative model itself.

**Comment by gserpep** [comment]
Thanks for the clarification! So, for `server_ss`, 128 is correct?

**Comment by SaraBabakN** [comment]
You are welcome and yes.
